https:
  enabled: true
config:
  issuer: https://dex.dex.svc.cluster.local:5556
  web:
    tlsCert: /etc/dex/tls/tls.crt
    tlsKey: /etc/dex/tls/tls.key
  storage:
    type: kubernetes
    config:
      inCluster: true
  staticClients:
    - id: jumpstarter
      name: jumpstarter
      secret: secret
  oauth2:
    passwordConnector: local
  enablePasswordDB: true
  staticPasswords:
    - email: "client-sample@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "client-sample"
      userID: "73bca0b9-9be6-4e73-a8fb-347c2ac23255"
    - email: "test-exporter-1@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-exporter-1"
      userID: "a4cb4de2-4467-4e5c-a42a-33be8783649d"
volumes:
  - name: tls
    secret:
      secretName: dex-tls
volumeMounts:
  - name: tls
    mountPath: /etc/dex/tls
service:
  type: NodePort
  ports:
    https:
      nodePort: 32000
