name: selftest
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
